# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: middleware.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'middleware.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10middleware.proto\"4\n\x0eServiceRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"&\n\x0fServiceResponse\x12\x13\n\x0boutput_text\x18\x01 \x01(\t2J\n\x11MiddlewareService\x12\x35\n\x0cRouteRequest\x12\x0f.ServiceRequest\x1a\x10.ServiceResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'middleware_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVICEREQUEST']._serialized_start=20
  _globals['_SERVICEREQUEST']._serialized_end=72
  _globals['_SERVICERESPONSE']._serialized_start=74
  _globals['_SERVICERESPONSE']._serialized_end=112
  _globals['_MIDDLEWARESERVICE']._serialized_start=114
  _globals['_MIDDLEWARESERVICE']._serialized_end=188
# @@protoc_insertion_point(module_scope)
