# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: summarization.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'summarization.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13summarization.proto\"\x1e\n\x0eSummaryRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\"\n\x0fSummaryResponse\x12\x0f\n\x07summary\x18\x01 \x01(\t2N\n\x14SummarizationService\x12\x36\n\rSummarizeText\x12\x0f.SummaryRequest\x1a\x10.SummaryResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'summarization_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUMMARYREQUEST']._serialized_start=23
  _globals['_SUMMARYREQUEST']._serialized_end=53
  _globals['_SUMMARYRESPONSE']._serialized_start=55
  _globals['_SUMMARYRESPONSE']._serialized_end=89
  _globals['_SUMMARIZATIONSERVICE']._serialized_start=91
  _globals['_SUMMARIZATIONSERVICE']._serialized_end=169
# @@protoc_insertion_point(module_scope)
